### ISSUE TITLE
How to make WordPress SEO by Yoast working with Aqua-Page-Builder

### ISSUE THREAD

**Issue by elrogue** [syamilmj/Aqua-Page-Builder#54]
Hello,

I'm using a theme who use your awesome plugin and my question is simple, how to make your plugin working with WordPress SEO by Yoast ?

Thanks a lot for your great work !

**Comment by mac1704** [comment]
Has this been answered as yet as i have the same question?

**Comment by monecchi** [comment]
In the past Yoast WordPress SEO plugin used to rely on a filter to help you add custom content to its analysis. The latest versions of the plugin is powered by what its developers call YoastSEO.js, which holds the logic behind the analysis. 

Since WordPress SEO version 3.3.1 (when I started using it), I noticed that the plugin is able to fetch data from shortcodes placed on page/post's textarea under the edit screen, including Aqua Page Builder template shotcode.

I can confirm it works, though you have to keep in mind you need to perform the SEO best practices hinted by the WordPress SEO plugin when building your templates with Aqua Page Builder.

I'm postings this from my phone, so no much room for details. I'll be posting some more specific tips regarding this issue soon. Keep watching it!

**Comment by monecchi** [comment]
<b>I'm afraid people are not really getting how easy is to use both plugins together.</b> If you're using Aqua Page Builder with along WordPress SEO, simply follow the common content creation guideline focused in SEO best practices while creating your templates with AQPB and WordPress SEO plugin will do the rest.

**So what gives?**
If you just came to this issue, chances are you might be feeling discouraged about using Yoast WordPress SEO plugin with along Aqua Page Builder. No need for that, keep reading and you'll see you're able to use both plugins without hurting your SEO!

In the past (not so long ago) Yoast WordPress SEO plugin used to have filter hooks so other plugins could add custom content to its analysis script. The most widely used filter was `wpseo_pre_analysis_post_content`,  [See the discussion here.](https://github.com/syamilmj/Aqua-Page-Builder/issues/130) However, the way it used to work was improved and changed over time.

**How does it work now?**
In order to validate a page/post's content, YoastSEO.js analysis picks up whatever it finds within the post/page edit screen _textarea_, including your **[shortcodes]**. Yes, it's that easy, place any shortcode while editing your page or post (including Aqua Page Builder template shortcode) and WordPress SEO will "scrap" its contents for analysis. Read about [YoastSEO.js design decisions](https://yoast.com/dev-blog/yoastseo-js-design-decisions/) and their shortcode solution [here](https://github.com/Yoast/wordpress-seo/blob/3.0/js/wp-seo-shortcode-plugin.js).

![captura de tela 2016-09-21 as 16 33 36](https://cloud.githubusercontent.com/assets/5252519/18726073/376672be-8019-11e6-8781-8f2293a42722.png)

**Yep it works!**

Since WordPress SEO version 3.3.1 (when I started using it), I'm able to see the plugin is indeed able to perfectly analyze my page's content by "scrapping" data from the Aqua Page Builder template shortcode. It means that once the shortcode is placed in the page/post's textarea, WordPress SEO plugin recognizes the shortcode's presence and starts validating its content. 

**So, what's the approach?** Pretty easy actually!
- You have WordPress SEO plugin latest update installed.
- You create a page and start improving your page's SEO by filling up the WordPress SEO plugin fields as you'd normally do. This includes the **Focus keyword**, the **Seo Title**, the **Meta Description**, the **Page/Post Thumbnails** etc.
- You then start building a template with Aqua Page Builder while keeping SEO best practices in mind so your AQPB template can match your page's SEO settings.
- Once you update the template created with Aqua Page Builder, you also should update the actual page where the template shortcode is placed so that the WordPress SEO plugin is able to recognize the template's recent changes.

**WordPress SEO Plugin is throwing a lot of bad validation notices about my template's content built with Aqua Page Builder, what's wrong?**
- Be sure you have WordPress SEO plugin latest version installed.
- Be sure you're following WordPress SEO analysis tips when building your templates, e.g: If it is complaining about how long your sentences are, go back to Aqua Page Builder template and fix those issues.
- For each and every WordPress SEO's notices, you wanna check those against both your page and Aqua Page Builder template's content. Eg.: WordPress SEO analysis says the focus keyword should appear in 1 or more subheadings, what do you do? You go back to your Aqua Page Builder template and make the necessary changes, then jump back to your page and update it. Then, right after that you'll see the analysis does not complain anymore about the lack of the focus keyword in subheadings.
- Keep managing the necessary changes according to WordPress SEO analysis hints until you have a good score. That's it!

**Should I really be worried about Aqua Page Builder not fully supporting WordPress SEO plugin? Would it hurt my SEO?**
Not actually. With recent versions of WordPress SEO plugin you don't need to do nothing to have your Aqua Page Builder template shortcode's content validated. However, you'll have to keep in mind you need to apply SEO best practices while building your AQPB templates. You should also follow the WordPress SEO plugin analysis notices and tips to fix any issues on your templates regarding the page's SEO score.

The code AQPB outputs for your template's content it's pretty clean and search engine friendly, and for search engines it's all that matters. The WordPress SEO plugin's validation will not hurt your SEO as long as you keep building your Aqua Page Builder's templates with SEO best practices in mind. YoastSEO.js analysis it's there to help you improve your content & get high SEO scores, take the most of it.

If your Aqua Page builder blocks offers you extended SEO settings, you'd be able to place `alt` and `title` tags for images, `rel` attribute on links & buttons as well other SEO related stuff. Otherwise, jus keep building your templates so they can match the SEO settings you've defined for the page that is going to hold the template's shortcode.

Good luck improving your SEO with AQPB and WordPress SEO plugin!
